#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/sistema15_.jar:$APPDIR/lib/core.jar:$APPDIR/lib/tritonus_share.jar:$APPDIR/lib/jl1.0.jar:$APPDIR/lib/mp3spi1.9.4.jar:$APPDIR/lib/minim-spi.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/jsminim.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/twitter4j213.jar:$APPDIR/lib/twitter4j-examples-2.1.3.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/RXTXcomm.jar:$APPDIR/lib/arduino.jar" sistema15_
